version: '3.8'

services:
  video-gallery:
    build: .
    container_name: video-gallery-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      # Bind mount for videos - change the left path to your host directory
      - ./videos:/app/public/videos:ro
      # Bind mount for QR codes - for easy extraction of generated QR codes
      - ./qr_codes:/app/public/qr_codes
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      # Set your base URL here for QR code generation
      - BASE_URL=http://localhost:3000
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
